name: CI/CD Pipeline for Multi-Cloud Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      run: |
        docker build -t my-docker-repo/my-app:latest ./app
        docker push my-docker-repo/my-app:latest

    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Update kubeconfig for EKS
      run: |
        aws eks update-kubeconfig --name eks-cluster

    - name: Deploy to EKS
      run: |
        helm upgrade --install my-app ./helm/app-chart

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Update kubeconfig for AKS
      run: |
        az aks get-credentials --resource-group aks-resource-group --name aks-cluster

    - name: Deploy to AKS
      run: |
        helm upgrade --install my-app ./helm/app-chart
